Layout refactor
migueldavideraso/html_editor pull request #8
Opened 2023-09-10 15:30 UTC by loannesdev

2023-09-10 18:28 UTC, migueldavideraso requested changes
Soluciona los problemas del selector con estilos globales, el tamaño del aside y del contenedor de los estilos. Eso es necesario para poder hacer el merge.
Lo del linter si quieres lo podemos hablar y hacerlo en una reunión. Si no puedes colocar el que gustes, pero lo importante es tener uno.

2023-09-10 18:28 UTC, migueldavideraso commented on src/app/App.svelte
No quites el selector ".container_app" (o cualquiera) cuando hay un ":global" delante, lo que pasa es que el estilo global afectará a toda la página y una forma de controlar que solo afecte a los estilos de nuestro paquete es con ese selector

2023-09-10 18:28 UTC, migueldavideraso commented on src/app/styles_panel/Styles.svelte
Aquí te cargaste los estilos de: ".styles_section :global(.elements_grid .input_group)"

2023-09-10 18:28 UTC, migueldavideraso commented on src/app/styles_panel/Styles.svelte
El contenedor de "<section class="styles_section"></section>" es para separar las opciones del header, cuando hay muchas opciones y hay un overflow el header se oculta, esto se puede solucionar con "position: sticky;". Pero deja el contenedor, ya que así se ve más amigable y podríamos cambiar las opciones de eliminar, duplicar y avanzadas a un footer para que así permanezcan visibles.

2023-09-10 18:28 UTC, migueldavideraso commented on src/app/styles_panel/components/text_editor/Main.svelte
Hay muchos cambios del estilo del código, no sé si ya tienes el linter. Para que lo subas y así estemos en un consenso.

2023-09-10 18:28 UTC, migueldavideraso commented on src/app/App.svelte
El elemento aside debe tener un width fijo, esto para que haya una mejor interacción. Ahí es necesario poner un min-width, ya que al ser un elemento flexible el width va cambiando. Los etilos del elemento aside ya se los coloco yo. Me gusto bastante como solucionaste el problema.

2023-09-10 18:29 UTC, migueldavideraso commented on src/app/styles_panel/Styles.svelte
La sección es: "styles_section"

2023-09-10 18:37 UTC, migueldavideraso commented on src/app/styles_panel/Styles.svelte
Debes retornarlos con la sección de los estilos. Si quieres podemos mejorar como son, pero es importante que no los cambies sin decirme.

2023-09-20 14:38 UTC, migueldavideraso commented on src/app/App.svelte
lo que pasa es que los style_options ya no son hijos de .container_app y por eso el selector no funciona para esos elementos. Pero con .main_container si funciona, ya que los style_options siguen siendo hijos de .main_container

2023-09-20 14:39 UTC, merged

2023-09-21 01:58 UTC, loannesdev commented on src/app/App.svelte
Vale lo quitaré pero ten en cuenta que los estilos que tiene el componente **style_options** no se van a aplicar. Cuando hice la modificación intenté de muchas maneras y donde si se aplicaron los estilos fue quitando el selector que mencionas o en lugar de *.container_app* poner *.main_container*

2023-09-21 01:58 UTC, loannesdev commented on src/app/styles_panel/components/text_editor/Main.svelte
Aún no lo he agregado, estaba esperando a terminar los cambios que ya me habías pedido para así después aplicar el linter

2023-09-21 01:58 UTC, loannesdev commented on src/app/styles_panel/Styles.svelte
Vale, voy a revertir los cambios